[tools]
#clang = "21.1"
cmake = "4.2"
#conan = "2.23"
ninja = "1.13"

[env]
#CMAKE_CXX_COMPILER = """{% if os() == "macos" -%}/opt/homebrew/opt/llvm/bin/clang++{%- elif os() == "windows" -%}C:/Program Files/LLVM/bin/clang++.exe{%- elif os() == "linux" -%}/opt/llvm-project/build/bin/clang{%- endif %}"""

# Mac Only
#CMAKE_OSX_SYSROOT = "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
#LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
#CPPFLAGS="-I/opt/homebrew/opt/zlib/include"
#PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

# Windows Only
#RC = "C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64/rc.exe"
